### ISSUE TITLE
Mario Kart 7

### ISSUE THREAD

**Issue by EmulatingGod** [Lime3DS/compatibility-list#21]
### Prerequisites

- [X] I have checked there is no currently open report for this game. (An updated report can be made for games with previously closed reports).
- [X] I have read through the contribution guide [here](https://github.com/Lime3DS/compatibility-list/blob/master/CONTRIBUTING.md) from start to finish.
- [X] I have played through this game from start to finish only using official releases of the Lime3DS emulator.
- [X] The OpenGL renderer was used for my entire playthrough.

### Rating

Great

### Description

I noticed a few stutters throughout my playthrough of Mario Kart 7 - a few slowdowns but there was nothing major. I didn't notice any glitchy textures throughout my playthrough of the game.

### Lime3DS Version

2118.2

### System Configuration

CPU: AMD Ryzen 5 5600X 6-Core Processor 3.70 GHz
GPU/Driver:
RAM: 16GB
OS: Windows 11 22631.4317

**Comment by OpenSauce04** [comment]
Mario Kart 7 already has a Great rating, and as you did not share an application ID in the title as required in the submission format, I am unsure of whether this is due to you using a region which hasn't been submitted or whether this report is redundant. Compatibility reports are only necessary when the rating has changed.

I will be closing this report for the above reasons.

**Comment by EmulatingGod** [comment]
@OpenSauce04 Huh, on my lime3ds its stated that Mario Kart 7 is untested, has there been an update I've missed? Why is it still displayed as untested?
